// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#pragma once

#include "Configuration.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeConfiguration final {
public:
    using CppType = ::libdc::Configuration;
    using JniType = jobject;

    using Boxed = NativeConfiguration;

    ~NativeConfiguration();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeConfiguration();
    friend ::djinni::JniClass<NativeConfiguration>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("gitv/xds/libdc/Configuration") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/util/ArrayList;Lgitv/xds/libdc/ProxyServer;Ljava/lang/String;Lgitv/xds/libdc/CertificateType;Lgitv/xds/libdc/TransportPolicy;ZZZZIILjava/lang/Integer;Ljava/lang/Integer;)V") };
    const jfieldID field_mIceServers { ::djinni::jniGetFieldID(clazz.get(), "mIceServers", "Ljava/util/ArrayList;") };
    const jfieldID field_mProxyServer { ::djinni::jniGetFieldID(clazz.get(), "mProxyServer", "Lgitv/xds/libdc/ProxyServer;") };
    const jfieldID field_mBindAddress { ::djinni::jniGetFieldID(clazz.get(), "mBindAddress", "Ljava/lang/String;") };
    const jfieldID field_mCertificateType { ::djinni::jniGetFieldID(clazz.get(), "mCertificateType", "Lgitv/xds/libdc/CertificateType;") };
    const jfieldID field_mIceTransportPolicy { ::djinni::jniGetFieldID(clazz.get(), "mIceTransportPolicy", "Lgitv/xds/libdc/TransportPolicy;") };
    const jfieldID field_mEnableIceTcp { ::djinni::jniGetFieldID(clazz.get(), "mEnableIceTcp", "Z") };
    const jfieldID field_mEnableIceUdpMux { ::djinni::jniGetFieldID(clazz.get(), "mEnableIceUdpMux", "Z") };
    const jfieldID field_mDisableAutoNegotiation { ::djinni::jniGetFieldID(clazz.get(), "mDisableAutoNegotiation", "Z") };
    const jfieldID field_mForceMediaTransport { ::djinni::jniGetFieldID(clazz.get(), "mForceMediaTransport", "Z") };
    const jfieldID field_mPortRangeBegin { ::djinni::jniGetFieldID(clazz.get(), "mPortRangeBegin", "I") };
    const jfieldID field_mPortRangeEnd { ::djinni::jniGetFieldID(clazz.get(), "mPortRangeEnd", "I") };
    const jfieldID field_mMtu { ::djinni::jniGetFieldID(clazz.get(), "mMtu", "Ljava/lang/Integer;") };
    const jfieldID field_mMaxMessageSize { ::djinni::jniGetFieldID(clazz.get(), "mMaxMessageSize", "Ljava/lang/Integer;") };
};

} // namespace djinni_generated
