// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

package gitv.xds.libdc;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

public interface DcMessageCallback {
    void onText(@NonNull String msg);

    void onBinary(@NonNull byte[] msg);
}
