// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

package gitv.xds.libdc;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

public interface GatheringStateCallback {
    void onStateChanged(@NonNull GatheringState state);
}
