// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

package gitv.xds.libdc;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

/** config start */
public enum IceServerType {
    STUN,
    TURN,
    ;
}
